---
title: "R Notebook"
output: html_notebook
---

---
title: "R Notebook"
output: html_notebook
---

Übungsblatt b


Aufgabe 1. <br />
1) (1+2)-4 <br />
2) 1+(2*4) <br />
3) (1/2)/4 <br />
4) 2\^(2\^4) 
```{r}
1+2-4
1+2*4
1/2/4
2^2^4
```

Aufgabe 2.
```{r}
rep("a", 6)
rep(c(1, 2, 3), c(3, 3, 3))
rep(c(1, 2, 3), c(3, 2, 1))
c(seq(1, 5, by=1), rev(seq(1, 4, by=1)))
```

Aufgabe 3. 
```{r}
x = c(1, 3, 5, 7, 9)
y = c(2, 3, 5, 7, 11, 13)

x + 1
y + 2
length(x)
length(y)
x + y
```

Aufgabe 4. <br />
1) 2 16 <br />
2) 3 <br />
3) 5 <br />
4) 7 <br />
5) 2 5 11  <br />
NA bedeutet "nicht angegeben"  <br />
6) 7 11 13 <br />
```{r}
x = c(1, 3, 5, 7, 9)
y = c(2, 3, 5, 7, 11, 13)

sum(x > 5)
sum(x[x > 5])
sum(x > 5|x < 3)

y[3]
y[-3]
y[x]
y[y >= 7]
```

Aufgabe 5. <br />
Wir benutzen die Funktion mean(name_der_spalte) wo name_der_spalte der Name der Spalte, deren Mittelwert wir bestimmen wollen.
```{r}
a <- c(1,2,3)
b <- c(2,3,2.5)
c <- c(1,1,1)

data.frame(a, b, c)
mean(a)
mean(b)
mean(c)
```





